spring:
  application:
    name: claquette
  datasource:
    url: "jdbc:postgresql://localhost:5432/claquette"
    username: docker
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    vertex:
      ai:
        gemini:
          project-id: PROJECT-ID
          location: LOCATION
          chat:
            options:
              model: gemini-1.0-pro-vision-001
              temperature: 0.4